---
title: "First Knit"
author: "Andrew Valles Tovar"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
The high school I attended was Antelope Valley High School. I graduated in 2015. I'm more familiar with math more than English. I'm not exactly creative with my writing so I ultimately prefer math. I did better in math than English.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have a Windows laptop at home. I'd rate myself a 9 on how well I know to use a computer. My internet connection speed is decently fast around 100 MBps for download.
  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
Andrew is fine.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to transfer to a CSU after fulfilling the transfer requirements in Antelope Valley College. For my greatest college subject interest, I saw that there used to a Chinese language learning course offered in the past in AVC, but learned it was discontinued so that was unfortunate. Currently I am trying to finish my IT Cybersecurity associate degree along with the general education transfer requirements. 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




